### PR TITLE
Githooks

### PR DESCRIPTION
**Pull request by szk2s**
Set up git hooks

### CODE REVIEW

**Comment by szk2s** [comment]
Hi @yuichkun,  I've set up git hooks as you said. Could you check it?

**Comment by yuichkun** [comment]
OK, I'll review this tonight

**Comment by yuichkun** [comment]
Oops, sorry I tried to send the last comment on the second commit. Please consider it so.

**Comment by satoshi-szk** [comment]
@yuichkun Thank you for your advice.  
I've changed like that.  
I think it is relevant to setting up githooks because the skipping is for faster pre-push command of git hooks.
Don't you think so?

**Pull request merged**
